web/router.ex
defmodule Blog.Router do
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
  end

  pipeline :api do
    plug :accepts, ~w(json)
  end

  scope "/", Blog do
    pipe_through :browser # Use the default browser stack

    resources "posts", PostsController
    get "/", PagesController, :index, as: :page

  end

  scope "/users", Blog do
    pipe_through :browser # Use the default browser stack

    get "/sign_up", RegistrationsController, :new, as: :registrations
    post "/sign_up", RegistrationsController, :create, as: :registrations
    get "/sign_in", SessionsController, :new, as: :sessions
    post "/sign_in", SessionsController, :create, as: :sessions
    delete "/sign_out", SessionsController, :delete, as: :sessions
  end

  # Other scopes may use custom stacks.
  # scope "/api", MyApp do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Blog.LayoutView do
  use Blog.Web, :view

end

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Elixir blog</a>
        </div>
        <div class="collapse navbar-collapse" >
          <%= if user = current_user(@conn) do %>
            <%= link("Sign out", to: sessions_path(@conn, :delete), method: :delete, form: [class: "navbar-text navbar-right"]) %>
            <p class="navbar-text navbar-right">Signed in as <%= user.email %></p>
          <% else %>
            <p class="navbar-text navbar-right">
              <%= link("Sign in", to: sessions_path(@conn, :new)) %>
            </p>
          <% end %>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= if message = get_flash(@conn, :notice) do %>
        <div class="alert alert-success" role="alert">
          <%= message %>
        </div>
      <% end %>
      <%= if message = get_flash(@conn, :alert) do %>
        <div class="alert alert-warning" role="alert">
          <%= message %>
        </div>
      <% end %>

      <%= @inner %>
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app")</script>
  </body>
</html>